# === Приложение ===
spring.application.name=order-service
server.port=8080

# === База данных ===
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/order_service}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:order_user}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:order_pass}
spring.datasource.driver-class-name=org.postgresql.Driver

# === JPA / Hibernate ===
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# === Flyway ===
spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration

# === Логирование ===
logging.level.by.shaaldy.orderservice=DEBUG